database:
  host: Cosmic-Echo.local
  port: 5432
  user: guest
  password: guest
  dbname: local
  sslmode: disable

replication:
  slot_name: walstreamer_slot
  publication_name: walstreamer_pub
  tables:
    - public.inventory
  standby_timeout: 10s

broker:
  type: nats
  hosts:
    - nats://localhost:4222
  topic: walstreamer.changes
  username: ""
  password: ""

lsn:
  type: file
  path: /tmp/walstreamer.lsn
  persist_interval: 5s

log:
  level: info
  format: console

storage:
  type: file
  path: /tmp/walstreamer
